
CREATE TABLE IF NOT EXISTS PROPERTY (
    ID  SERIAL NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    NUMBER INTEGER NOT NULL,
    COMPLEMENT VARCHAR(200) NOT NULL,
    PROPERTY_TYPE VARCHAR(100) NOT NULL,
    PROPERTY_PAID_OFF BOOLEAN  DEFAULT TRUE,
    CONSTRAINT PK_PROPERTY PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS SIMULATION (
    ID  SERIAL NOT NULL,
    ESTIMATED_VALUE DECIMAL(12, 2) NOT NULL,
    LOAN DECIMAL(12, 2) NOT NULL,
    DEADLINE INTEGER NOT NULL,
    REASON VARCHAR(250) NOT NULL,
    PROPERTY_PAID_OFF BOOLEAN  DEFAULT TRUE,
    CONSTRAINT PK_SIMULATION PRIMARY KEY (ID)
    );


CREATE TABLE IF NOT EXISTS SIMULATION_AND_PROPERTY (
    ID  SERIAL NOT NULL,
    SIMULATION_ID BIGINT NOT NULL,
    PROPERTY_ID BIGINT NOT NULL,
    CONSTRAINT PK_SIMULATION_AND_PROPERTY PRIMARY KEY (ID),
    CONSTRAINT FK_SIMULATION_AND_PROPERTY_SIMULATION FOREIGN KEY (SIMULATION_ID) REFERENCES SIMULATION(ID),
    CONSTRAINT FK_SIMULATION_AND_PROPERTY_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(ID)
    );

CREATE TABLE IF NOT EXISTS PERSON (
    ID  SERIAL NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    MAIL VARCHAR(150) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    TAX_ID VARCHAR(14) DEFAULT TRUE,
    LEGAL_PERSON BOOLEAN  DEFAULT FALSE,
    INCOME DECIMAL(12,2)  DEFAULT 0,
    PROFESSIONAL_SITUATION_TYPE VARCHAR(100)  NOT NULL,
    CONSTRAINT PK_PERSON PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS PERSON_AND_SIMULATION (
    ID  SERIAL NOT NULL,
    PERSON_ID BIGINT NOT NULL,
    SIMULATION_ID BIGINT NOT NULL,
    CONSTRAINT PK_PERSON_AND_SIMULATION PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_AND_SIMULATION_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
    CONSTRAINT FK_PERSON_AND_SIMULATION_SIMULATION FOREIGN KEY (SIMULATION_ID) REFERENCES SIMULATION(ID)
    );



CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID  SERIAL NOT NULL,
    FIRST_NAME VARCHAR(150) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
    );

